### ISSUE TITLE
Todo before production

### ISSUE THREAD

**Issue by eirsyl** [webkom/brus-backend#2]
- [x] Remove documentation from urls.py
- [x] Maybe create a custom login view
- [x] Remove static urls from production
- [x] Remove the settings/settings.py file
- [x] Remove celery options
- [x] Change ALLOWED_HOSTS default in production.py
- [x] REMOVE ABAKUS_TOKEN from opensource repository (base.py, production.py) 👊 
- [x] Restrict to Webkom group (django-auth-abakus)
- [x] settings/**init**.py line 14 lego?
- [x] templates/brus/index.html line 98-114?
- [x] liste/models.py line 35-52?

Consider adding isort, flake8, tox and a readme.

**Comment by warlo** [comment]
The celery options is there because of the testrunner. It was suggested to create some tests, could be an ok task 😊

**Comment by eirsyl** [comment]
The test-runner runs celery tasks synchronous, but since this project not use celery you can remove the testrunner.
